using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace StealMyPaintscheme.Api.Migrations
{
    /// <inheritdoc />
    public partial class ReSeedAdminUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Username"" text NOT NULL,
                    ""Password"" text NOT NULL,
                    ""Email"" text NOT NULL,
                    ""IsAdmin"" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Username", "Password", "Email", "IsAdmin" },
                values: new object[] { "admin", "$2a$11$0WfJ9kZ2A8M6M0zI8V/XUeW/p0K.V8yX4n6D3L.yV7n9yX4n6D3L.", "admin@stealmypaintscheme.nl", true });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Username",
                keyValue: "admin");
        }
    }
}
